### ISSUE TITLE
Email on changes ?

### ISSUE THREAD

**Issue by sladecraven** [Blaok/nextcloud-inotifyscan#12] opened 2019-08-14 09:54 UTC
Hi, 
This small service is working perfectly, and changes in my external folders are seen in the Web interface, but i would like to send activity emails also. It does not work on my side, or at least i miss something (Nextcloud 16.0.3, latest nextcloud-inotifyscan).

Any hint or idea ?

Thanks !

**Comment by Blaok** [comment] 2019-08-14 20:50
Hi. Thanks for your interest. As I mentioned in [#11](https://github.com/Blaok/nextcloud-inotifyscan/issues/11#issuecomment-515097917),

> About triggers for sending emails, I think they are out of the scope of this project. Ideally they should be triggered by the updates of the database, which themselves can be triggered by this script, or Nextcloud's built-in scanning mechanism.

That said, Nextcloud has an official [activity app](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/activity_configuration.html). You might want to take a look, although I personally am not using it.

**Comment by sladecraven** [comment] 2019-08-14 21:19
Ah yes, in fact my post is not clear : i am using already the Activity app, which triggers email properly for changes when files are uploaded (for example) thru the web interface. But the files added thru the local filesystem and detected by your tool never triggers the email. Do you know what are the potential differences inside Nextcloud between file change from the Web interface and file changes detected by your tool that could explain that behavior ?

**Comment by Blaok** [comment] 2019-08-15 03:03
Ah. That's a good question. `nextcloud-inotifyscan` uses `occ files:scan` to update the Nextcloud database so the problem here is that `occ files:scan` does not trigger emails from the Activity app. Let's first [figure out if this is an intended behavior](https://github.com/nextcloud/activity/issues/387).

**Comment by sladecraven** [comment] 2019-08-15 06:41
Thanks ! Let's see the responses now :)

**Comment by Blaok** [comment] 2022-01-28 03:54
Closing as a duplicate of the upstream [#233](https://github.com/nextcloud/activity/issues/233)

**Closed by Blaok** 2022-01-28 03:54 UTC
Labels: duplicate
